import {
  ActivityLevel,
  DietaryRestriction,
  ExerciseType,
  Goal,
  IntensityLevel,
  type Food,
  type TasteProfile,
  type UserProfile,
  WorkRoutine,
} from "@prisma/client";

const FIXTURE_DATE = new Date("2026-04-08T12:00:00.000Z");

export function makeFood(overrides: Partial<Food> = {}): Food {
  return {
    id: "food-default",
    name: "Alimento Base",
    category: "carboidrato",
    brand: null,
    unit: "g",
    caloriesKcal: 100,
    proteinG: 10,
    fatG: 5,
    carbsG: 10,
    fiberG: 0,
    sugarG: 0,
    vitaminA_UG: 0,
    vitaminC_MG: 0,
    vitaminD_UG: 0,
    vitaminE_MG: 0,
    vitaminK_UG: 0,
    vitaminB1_MG: 0,
    vitaminB2_MG: 0,
    vitaminB3_MG: 0,
    vitaminB5_MG: 0,
    vitaminB6_MG: 0,
    vitaminB9_UG: 0,
    vitaminB12_UG: 0,
    calcium_MG: 0,
    iron_MG: 0,
    magnesium_MG: 0,
    zinc_MG: 0,
    potassium_MG: 0,
    sodium_MG: 0,
    selenium_UG: 0,
    phosphorus_MG: 0,
    choline_MG: 0,
    manganese_MG: 0,
    createdAt: FIXTURE_DATE,
    updatedAt: FIXTURE_DATE,
    ...overrides,
  };
}

export function makeUserProfile(overrides: Partial<UserProfile> = {}): UserProfile {
  return {
    id: "profile-default",
    userId: "user-default",
    age: 30,
    sex: "MALE",
    heightCm: 180,
    weightKg: 80,
    bodyFatPercentage: 20,
    country: "BR",
    state: "SP",
    city: "Sao Paulo",
    activityLevel: ActivityLevel.MODERATE,
    exerciseFrequency: 4,
    primaryExerciseType: ExerciseType.WEIGHTLIFTING,
    exerciseDurationMin: 60,
    exerciseIntensity: IntensityLevel.MODERATE,
    mealsPerDay: 4,
    workRoutine: WorkRoutine.CLT_9_TO_5,
    dietaryRestrictions: DietaryRestriction.NONE,
    weeklyFoodBudget: 250,
    goal: Goal.MAINTENANCE,
    tdee: null,
    targetCalories: null,
    targetProteinG: null,
    targetFatG: null,
    targetCarbsG: null,
    createdAt: FIXTURE_DATE,
    updatedAt: FIXTURE_DATE,
    ...overrides,
  };
}

export function makeTasteProfile(overrides: Partial<TasteProfile> = {}): TasteProfile {
  return {
    id: "taste-default",
    userId: "user-default",
    stapleFoods: "[]",
    aversions: "[]",
    sweetPreference: 3,
    saltyPreference: 3,
    spicyTolerance: 2,
    cookingSkill: 3,
    cookingTime: 30,
    favoriteFoods: "[]",
    createdAt: FIXTURE_DATE,
    updatedAt: FIXTURE_DATE,
    ...overrides,
  };
}
